local M = {}

function M.setup()
    local colors = {
        background = "#442C17",
        light_brown = "#D0A076",
        tan = "#D5AB85",
        soft_red = "#FF8F8F",
        soft_pink = "#D4738E",
        red_pink = "#995D81",
        orange = "#BE8651",
        light_orange = "#FAAD6E",
        orange2 = "#D7B67D",
        light_green = "#D8FFDD",
        gold = "#D9D196",
        strong_yellow = "#CABF6D",
        solid_yellow = "#E3B505",
        white = "#CCCCCC",
        light_blue = "#4A321C",
    }

    local highlights = {
        -- Editor
        Normal = { fg = colors.white, bg = colors.background },
        NormalFloat = { fg = colors.white, bg = colors.background },
        FloatBorder = { fg = colors.gold, bg = colors.background },

        -- Cursor
        Cursor = { fg = colors.background, bg = colors.light_orange },
        CursorLine = { bg = colors.light_blue },
        CursorColumn = { bg = colors.light_blue },

        -- Selection
        Visual = { bg = colors.light_blue, fg = colors.light_orange },
        VisualNOS = { bg = colors.light_blue, fg = colors.light_orange },

        -- Search
        Search = { fg = colors.background, bg = colors.light_green },
        IncSearch = { fg = colors.background, bg = colors.light_orange },

        -- Line numbers
        LineNr = { fg = colors.tan },
        LineNrAbove = { fg = colors.tan },
        LineNrBelow = { fg = colors.tan },
        CursorLineNr = { fg = colors.light_orange, bold = true },

        -- Signs
        SignColumn = { fg = colors.tan, bg = colors.background },
        FoldColumn = { fg = colors.tan, bg = colors.background },
        Folded = { fg = colors.tan, bg = colors.light_blue },

        -- Statusline
        StatusLine = { fg = colors.white, bg = colors.light_blue },
        StatusLineNC = { fg = colors.tan, bg = colors.light_blue },

        -- Tabline
        TabLine = { fg = colors.tan, bg = colors.light_blue },
        TabLineFill = { bg = colors.light_blue },
        TabLineSel = { fg = colors.light_orange, bg = colors.background },

        -- Messages
        ModeMsg = { fg = colors.light_orange, bold = true },
        MoreMsg = { fg = colors.light_orange },
        WarningMsg = { fg = colors.soft_red },
        ErrorMsg = { fg = colors.soft_red },

        -- Completion
        Pmenu = { fg = colors.white, bg = colors.light_blue },
        PmenuSel = { fg = colors.background, bg = colors.light_orange },
        PmenuSbar = { bg = colors.light_blue },
        PmenuThumb = { bg = colors.tan },

        -- Diffs
        DiffAdd = { fg = colors.light_green, bg = colors.background },
        DiffDelete = { fg = colors.soft_red, bg = colors.background },
        DiffChange = { fg = colors.gold, bg = colors.background },
        DiffText = { fg = colors.light_orange, bg = colors.light_blue },

        -- Spelling
        SpellBad = { fg = colors.soft_red, undercurl = true },
        SpellCap = { fg = colors.soft_red, undercurl = true },
        SpellLocal = { fg = colors.light_blue, undercurl = true },
        SpellRare = { fg = colors.gold, undercurl = true },

        -- Syntax groups
        Comment = { fg = colors.tan },
        String = { fg = colors.orange2 },
        Character = { fg = colors.orange2 },
        Number = { fg = colors.light_green },
        Float = { fg = colors.light_green },
        Boolean = { fg = colors.soft_red },
        Identifier = { fg = colors.white },
        Function = { fg = colors.strong_yellow },
        Statement = { fg = colors.light_orange },
        Keyword = { fg = colors.light_orange },
        Conditional = { fg = colors.light_orange },
        Repeat = { fg = colors.light_orange },
        Label = { fg = colors.light_orange },
        Operator = { fg = colors.light_orange },
        Exception = { fg = colors.soft_red },
        PreProc = { fg = colors.light_orange },
        Include = { fg = colors.light_orange },
        Define = { fg = colors.light_orange },
        Macro = { fg = colors.light_orange },
        Type = { fg = colors.strong_yellow, bold = true },
        StorageClass = { fg = colors.light_orange },
        Structure = { fg = colors.strong_yellow },
        Typedef = { fg = colors.strong_yellow },
        Special = { fg = colors.light_orange },
        SpecialChar = { fg = colors.light_orange },
        Tag = { fg = colors.light_orange },
        Delimiter = { fg = colors.light_orange },

        -- Treesitter
        ["@attribute"] = { fg = colors.light_brown },
        ["@attribute.builtin"] = { fg = colors.light_brown },
        ["@boolean"] = { fg = colors.soft_red },
        ["@character"] = { fg = colors.orange2 },
        ["@character.special"] = { fg = colors.light_blue, italic = true },
        ["@comment"] = { fg = colors.tan },
        ["@comment.documentation"] = { fg = colors.tan },
        ["@comment.error"] = { fg = colors.red_pink },
        ["@comment.note"] = { fg = colors.light_brown },
        ["@comment.warning"] = { fg = colors.soft_red },
        ["@constant"] = { fg = colors.soft_pink },
        ["@constant.builtin"] = { fg = colors.soft_pink },
        ["@constant.macro"] = { fg = colors.soft_pink },
        ["@constructor"] = { fg = colors.light_brown },
        ["@error"] = { fg = colors.soft_red },
        ["@exception"] = { fg = colors.soft_red },
        ["@field"] = { fg = colors.orange },
        ["@float"] = { fg = colors.light_green },
        ["@function"] = { fg = colors.strong_yellow },
        ["@function.builtin"] = { fg = colors.soft_red },
        ["@function.call"] = { fg = colors.strong_yellow },
        ["@function.macro"] = { fg = colors.strong_yellow },
        ["@function.method.call"] = { fg = colors.gold, italic = true },
        ["@include"] = { fg = colors.light_orange },
        ["@keyword"] = { fg = colors.light_orange, italic = true },
        ["@keyword.conditional"] = { fg = colors.light_orange },
        ["@keyword.coroutine"] = { fg = colors.light_green },
        ["@keyword.debug"] = { fg = colors.light_orange },
        ["@keyword.directive"] = { fg = colors.light_orange },
        ["@keyword.exception"] = { fg = colors.tan, italic = true },
        ["@keyword.function"] = { fg = colors.light_orange },
        ["@keyword.import"] = { fg = colors.light_orange, bold = true, italic = true },
        ["@keyword.operator"] = { fg = colors.light_orange },
        ["@keyword.repeat"] = { fg = colors.light_orange },
        ["@keyword.return"] = { fg = colors.light_orange },
        ["@keyword.storage"] = { fg = colors.light_orange },
        ["@label"] = { fg = colors.light_orange },
        ["@markup"] = { fg = colors.white },
        ["@markup.emphasis"] = { italic = true },
        ["@markup.environment"] = { fg = colors.light_orange },
        ["@markup.environment.name"] = { fg = colors.light_orange },
        ["@markup.heading"] = { fg = colors.light_orange, bold = true },
        ["@markup.link"] = { fg = colors.strong_yellow, underline = true },
        ["@markup.link.label"] = { fg = colors.strong_yellow },
        ["@markup.link.url"] = { fg = colors.strong_yellow, underline = true },
        ["@markup.list"] = { fg = colors.light_orange },
        ["@markup.list.checked"] = { fg = colors.light_green },
        ["@markup.list.unchecked"] = { fg = colors.light_orange },
        ["@markup.quote"] = { fg = colors.tan },
        ["@markup.raw"] = { fg = colors.orange2 },
        ["@markup.raw.block"] = { fg = colors.orange2 },
        ["@markup.strikethrough"] = { strikethrough = true },
        ["@markup.strong"] = { bold = true },
        ["@markup.underline"] = { underline = true },
        ["@module"] = { fg = colors.white },
        ["@module.builtin"] = { fg = colors.soft_pink },
        ["@namespace"] = { fg = colors.white },
        ["@number"] = { fg = colors.light_green },
        ["@operator"] = { fg = colors.light_orange },
        ["@parameter"] = { fg = colors.orange },
        ["@parameter.builtin"] = { fg = colors.orange },
        ["@parameter.reference"] = { fg = colors.orange },
        ["@property"] = { fg = colors.solid_yellow, italic = true },
        ["@punctuation"] = { fg = colors.light_orange },
        ["@punctuation.bracket"] = { fg = colors.gold, bold = true },
        ["@punctuation.delimiter"] = { fg = colors.light_orange },
        ["@punctuation.special"] = { fg = colors.light_orange },
        ["@string"] = { fg = colors.orange2 },
        ["@string.documentation"] = { fg = colors.tan },
        ["@string.escape"] = { fg = colors.light_green },
        ["@string.regex"] = { fg = colors.orange2 },
        ["@string.special"] = { fg = colors.light_blue, italic = true },
        ["@symbol"] = { fg = colors.soft_pink },
        ["@tag"] = { fg = colors.light_orange },
        ["@tag.attribute"] = { fg = colors.orange },
        ["@tag.builtin"] = { fg = colors.gold, bold = true },
        ["@tag.delimiter"] = { fg = colors.light_orange },
        ["@text"] = { fg = colors.white },
        ["@text.danger"] = { fg = colors.soft_red },
        ["@text.diff.add"] = { fg = colors.light_green },
        ["@text.diff.delete"] = { fg = colors.soft_red },
        ["@text.note"] = { fg = colors.light_brown },
        ["@text.reference"] = { fg = colors.strong_yellow },
        ["@text.title"] = { fg = colors.light_orange, bold = true },
        ["@text.todo"] = { fg = colors.light_orange, bold = true },
        ["@text.underline"] = { underline = true },
        ["@text.warning"] = { fg = colors.soft_red },
        ["@type"] = { fg = colors.strong_yellow, bold = true },
        ["@type.builtin"] = { fg = colors.soft_pink },
        ["@type.definition"] = { fg = colors.strong_yellow },
        ["@type.qualifier"] = { fg = colors.light_orange },
        ["@variable"] = { fg = colors.white },
        ["@variable.builtin"] = { fg = colors.orange, italic = true },
        ["@variable.member"] = { fg = colors.orange, italic = true },
        ["@variable.parameter"] = { fg = colors.orange },
        ["@variable.parameter.builtin"] = { fg = colors.orange },

        -- Git
        ["@diff.plus"] = { fg = colors.light_green },
        ["@diff.minus"] = { fg = colors.soft_red },
        ["@diff.delta"] = { fg = colors.light_green },

        -- Language specific
        makeTarget = { fg = colors.light_orange },

        -- Non Tree sitter
        qfFileName = { fg = colors.light_brown },
        QuickFixLine = { fg = colors.light_brown, bold = true, italic = true },
        qfLineNr = { fg = colors.light_brown, bold = true },

        -- Oil
        OilDir = { fg = colors.gold, italic = true },
        OilDirIcon = { fg = colors.gold, italic = true },
        OilFile = { fg = colors.white },
        OilFileIcon = { fg = colors.white },
        OilSize = { fg = colors.tan },
        OilTime = { fg = colors.tan },
        OilPermRead = { fg = colors.light_green },
        OilPermWrite = { fg = colors.light_orange },
        OilPermExe = { fg = colors.light_orange },
        OilCopy = { fg = colors.soft_pink, italic = true, bold = true },
        OilMove = { fg = colors.soft_pink, italic = true, bold = true },
        OilChange = { fg = colors.soft_pink, italic = true, bold = true },
        OilCreate = { fg = colors.soft_pink, italic = true, bold = true },
        OilDelete = { fg = colors.soft_pink, italic = true },
        OilRename = { fg = colors.soft_red, italic = true },
        OilTrash = { fg = colors.gold, italic = true, bold = true },
        OilPurge = { fg = colors.gold, italic = true, bold = true },
        OilHidden = { fg = colors.red_pink, italic = true },
        OilSocket = { fg = colors.gold, italic = true },
        OilRestore = { fg = colors.gold, italic = true },
        OilDirHidden = { fg = colors.gold, italic = true },
        OilFileHidden = { fg = colors.gold, italic = true },
        OilLinkHidden = { fg = colors.gold, italic = true },
        OilLinkTarget = { fg = colors.gold, italic = true },
        OilSocketHidden = { fg = colors.gold, italic = true },
        OilTrashSourcePath = { fg = colors.gold, italic = true },
        OilLinkTargetHidden = { fg = colors.gold, italic = true },
        OilOrphanLinkHidden = { fg = colors.gold, italic = true },
        OilOrphanLinkTarget = { fg = colors.gold, italic = true },
        OilOrphanLinkTargetHidden = { fg = colors.gold, italic = true },

        -- Lazy
        LazyH1 = { fg = colors.light_orange, bold = true },
        LazyButton = { fg = colors.white, bg = colors.light_blue },
        LazyButtonActive = { fg = colors.background, bg = colors.light_orange },

        -- Telescope
        TelescopeNormal = { fg = colors.white, bg = colors.background },
        TelescopeBorder = { fg = colors.tan, bg = colors.background },
        TelescopeSelection = { fg = colors.background, bg = colors.light_orange },
        TelescopeMultiSelection = { fg = colors.background, bg = colors.tan },
        TelescopeMatching = { fg = colors.orange2, bold = true },

        -- Netrw (file browser)
        Directory = { fg = colors.gold, bold = true },
        ExeFile = { fg = colors.light_orange },

        -- Cursor
        CurSearch = { fg = colors.background, bg = colors.light_orange },

        -- Diagnostics
        DiagnosticError = { fg = colors.soft_red },
        DiagnosticWarn = { fg = colors.soft_red },
        DiagnosticInfo = { fg = colors.gold },
        DiagnosticHint = { fg = colors.light_brown },
        DiagnosticOk = { fg = colors.light_green },
        DiagnosticUnderlineError = { undercurl = true, sp = colors.soft_red },
        DiagnosticUnderlineWarn = { undercurl = true, sp = colors.soft_red },
        DiagnosticUnderlineInfo = { undercurl = true, sp = colors.gold },
        DiagnosticUnderlineHint = { undercurl = true, sp = colors.light_brown },
        DiagnosticUnderlineOk = { undercurl = true, sp = colors.light_green },
        DiagnosticVirtualTextError = { fg = colors.soft_red },
        DiagnosticVirtualTextWarn = { fg = colors.soft_red },
        DiagnosticVirtualTextInfo = { fg = colors.gold },
        DiagnosticVirtualTextHint = { fg = colors.light_brown },
        DiagnosticVirtualTextOk = { fg = colors.light_green },
        DiagnosticSignError = { fg = colors.soft_red },
        DiagnosticSignWarn = { fg = colors.soft_red },
        DiagnosticSignInfo = { fg = colors.gold },
        DiagnosticSignHint = { fg = colors.light_brown },
        DiagnosticSignOk = { fg = colors.light_green },
        DiagnosticFloatingInfo = { fg = colors.gold, bg = colors.background },
        Debug = { fg = colors.light_green, bg = colors.background },

        -- LSP hover and floating windows
        LspInfoBorder = { fg = colors.tan, bg = colors.background },
        LspSignatureActiveParameter = { bg = colors.light_blue, bold = true },
        LspCodeLens = { fg = colors.tan },
        LspCodeLensSign = { fg = colors.tan },
        LspCodeLensSeparator = { fg = colors.tan },

        -- LSP references
        LspReferenceText = { bg = colors.light_blue },
        LspReferenceRead = { bg = colors.light_blue },
        LspReferenceWrite = { bg = colors.light_blue },

        -- LSP inlay hints
        LspInlayHint = { fg = colors.tan, italic = true },

        -- LSP semantic tokens (fallback)
        ["@lsp.type.class"] = { fg = colors.strong_yellow },
        ["@lsp.type.comment"] = { fg = colors.tan },
        ["@lsp.type.decorator"] = { fg = colors.light_orange },
        ["@lsp.type.enum"] = { fg = colors.strong_yellow },
        ["@lsp.type.enumMember"] = { fg = colors.soft_pink },
        ["@lsp.type.event"] = { fg = colors.light_orange },
        ["@lsp.type.function"] = { fg = colors.strong_yellow },
        ["@lsp.type.interface"] = { fg = colors.strong_yellow },
        ["@lsp.type.keyword"] = { fg = colors.light_orange },
        ["@lsp.type.macro"] = { fg = colors.light_orange },
        ["@lsp.type.method"] = { fg = colors.strong_yellow },
        ["@lsp.type.modifier"] = { fg = colors.light_orange },
        ["@lsp.type.namespace"] = { fg = colors.white },
        ["@lsp.type.number"] = { fg = colors.light_green },
        ["@lsp.type.operator"] = { fg = colors.light_orange },
        ["@lsp.type.parameter"] = { fg = colors.orange },
        ["@lsp.type.property"] = { fg = colors.orange },
        ["@lsp.type.regexp"] = { fg = colors.orange2 },
        ["@lsp.type.string"] = { fg = colors.orange2 },
        ["@lsp.type.struct"] = { fg = colors.strong_yellow },
        ["@lsp.type.structMember"] = { fg = colors.orange },
        ["@lsp.type.typeParameter"] = { fg = colors.strong_yellow },
        ["@lsp.type.type"] = { fg = colors.strong_yellow },
        ["@lsp.type.variable"] = { fg = colors.white },

        Changed = { fg = colors.light_green, bg = colors.background },

        -- CMP
        CmpItemAbbr = { fg = colors.light_brown, italic = true },
        CmpItemKind = { fg = colors.light_brown, italic = true },
        CmpItemMenu = { fg = colors.light_brown, italic = true },
        CmpItemKindEnum = { fg = colors.light_brown, italic = true },
        CmpItemKindFile = { fg = colors.light_brown, italic = true },
        CmpItemKindText = { fg = colors.light_brown, italic = true },
        CmpItemKindUnit = { fg = colors.light_brown, italic = true },
        CmpItemAbbrMatch = { fg = colors.light_brown, italic = true },
        CmpItemKindClass = { fg = colors.light_brown, italic = true },
        CmpItemKindColor = { fg = colors.light_brown, italic = true },
        CmpItemKindEvent = { fg = colors.light_brown, italic = true },
        CmpItemKindField = { fg = colors.light_brown, italic = true },
        CmpItemKindValue = { fg = colors.light_brown, italic = true },
        CmpItemKindFolder = { fg = colors.light_brown, italic = true },
        CmpItemKindMethod = { fg = colors.light_brown, italic = true },
        CmpItemKindModule = { fg = colors.light_brown, italic = true },
        CmpItemKindStruct = { fg = colors.light_brown, italic = true },
        CmpItemAbbrDefault = { fg = colors.light_brown, italic = true },
        CmpItemKindDefault = { fg = colors.light_brown, italic = true },
        CmpItemKindKeyword = { fg = colors.light_brown, italic = true },
        CmpItemKindSnippet = { fg = colors.light_brown, italic = true },
        CmpItemMenuDefault = { fg = colors.light_brown, italic = true },
        CmpItemKindConstant = { fg = colors.light_brown, italic = true },
        CmpItemKindFunction = { fg = colors.light_brown, italic = true },
        CmpItemKindOperator = { fg = colors.light_brown, italic = true },
        CmpItemKindProperty = { fg = colors.light_brown, italic = true },
        CmpItemKindVariable = { fg = colors.light_brown, italic = true },
        CmpItemKindInterface = { fg = colors.light_brown, italic = true },
        CmpItemKindReference = { fg = colors.light_brown, italic = true },
        CmpItemAbbrDeprecated = { fg = colors.light_brown, italic = true },
        CmpItemAbbrMatchFuzzy = { fg = colors.light_brown, italic = true },
        CmpItemKindEnumMember = { fg = colors.light_brown, italic = true },
        CmpItemKindConstructor = { fg = colors.light_brown, italic = true },
        CmpItemKindEnumDefault = { fg = colors.light_brown, italic = true },
        CmpItemKindFileDefault = { fg = colors.light_brown, italic = true },
        CmpItemKindTextDefault = { fg = colors.light_brown, italic = true },
        CmpItemKindUnitDefault = { fg = colors.light_brown, italic = true },
        CmpItemAbbrMatchDefault = { fg = colors.light_brown, italic = true },
        CmpItemKindClassDefault = { fg = colors.light_brown, italic = true },
        CmpItemKindColorDefault = { fg = colors.light_brown, italic = true },
        CmpItemKindEventDefault = { fg = colors.light_brown, italic = true },
        CmpItemKindFieldDefault = { fg = colors.light_brown, italic = true },
        CmpItemKindValueDefault = { fg = colors.light_brown, italic = true },
        CmpItemKindFolderDefault = { fg = colors.light_brown, italic = true },
        CmpItemKindMethodDefault = { fg = colors.light_brown, italic = true },
        CmpItemKindModuleDefault = { fg = colors.light_brown, italic = true },
        CmpItemKindStructDefault = { fg = colors.light_brown, italic = true },
        CmpItemKindTypeParameter = { fg = colors.light_brown, italic = true },
        CmpItemKindKeywordDefault = { fg = colors.light_brown, italic = true },
        CmpItemKindSnippetDefault = { fg = colors.light_brown, italic = true },
        CmpItemKindConstantDefault = { fg = colors.light_brown, italic = true },
        CmpItemKindFunctionDefault = { fg = colors.light_brown, italic = true },
        CmpItemKindOperatorDefault = { fg = colors.light_brown, italic = true },
        CmpItemKindPropertyDefault = { fg = colors.light_brown, italic = true },
        CmpItemKindVariableDefault = { fg = colors.light_brown, italic = true },
        CmpItemKindInterfaceDefault = { fg = colors.light_brown, italic = true },
        CmpItemKindReferenceDefault = { fg = colors.light_brown, italic = true },
        CmpItemAbbrDeprecatedDefault = { fg = colors.light_brown, italic = true },
        CmpItemAbbrMatchFuzzyDefault = { fg = colors.light_brown, italic = true },
        CmpItemKindEnumMemberDefault = { fg = colors.light_brown, italic = true },
        CmpItemKindConstructorDefault = { fg = colors.light_brown, italic = true },
        CmpItemKindTypeParameterDefault = { fg = colors.light_brown, italic = true },

        -- Oil
        OilDir = { fg = colors.gold, italic = true },
        OilCopy = { fg = colors.soft_pink, italic = true, bold = true },
        OilMove = { fg = colors.soft_pink, italic = true, bold = true },
        OilPurge = { fg = colors.gold, italic = true, bold = true },
        OilTrash = { fg = colors.gold, italic = true, bold = true },
        OilChange = { fg = colors.soft_pink, italic = true, bold = true },
        OilCreate = { fg = colors.soft_pink, italic = true, bold = true },
        OilDelete = { fg = colors.soft_pink, italic = true },
        OilHidden = { fg = colors.red_pink, italic = true },
        OilSocket = { fg = colors.gold, italic = true },
        OilDirIcon = { fg = colors.gold, italic = true },
        OilRestore = { fg = colors.gold, italic = true },
        OilDirHidden = { fg = colors.gold, italic = true },
        OilFileHidden = { fg = colors.gold, italic = true },
        OilLinkHidden = { fg = colors.gold, italic = true },
        OilLinkTarget = { fg = colors.gold, italic = true },
        OilSocketHidden = { fg = colors.gold, italic = true },
        OilTrashSourcePath = { fg = colors.gold, italic = true },
        OilLinkTargetHidden = { fg = colors.gold, italic = true },
        OilOrphanLinkHidden = { fg = colors.gold, italic = true },
        OilOrphanLinkTarget = { fg = colors.gold, italic = true },
        OilOrphanLinkTargetHidden = { fg = colors.gold, italic = true },
        OilFile = { fg = colors.white },
        OilFileIcon = { fg = colors.white },
        OilSize = { fg = colors.tan },
        OilTime = { fg = colors.tan },
        OilPermRead = { fg = colors.light_green },
        OilPermWrite = { fg = colors.light_orange },
        OilPermExe = { fg = colors.light_orange },
        OilRename = { fg = colors.soft_red, italic = true },

        -- Lazy
        LazyH1 = { fg = colors.light_orange, bold = true },
        LazyButton = { fg = colors.white, bg = colors.light_blue },
        LazyButtonActive = { fg = colors.background, bg = colors.light_orange },

        -- Telescope (add missing)
        TelescopeNormal = { fg = colors.white, bg = colors.background },
        TelescopeBorder = { fg = colors.tan, bg = colors.background },
        TelescopeSelection = { fg = colors.background, bg = colors.light_orange },
        TelescopeMultiSelection = { fg = colors.background, bg = colors.tan },

        -- Netrw (file browser)
        Directory = { fg = colors.gold, bold = true },
        ExeFile = { fg = colors.light_orange },

        -- Diagnostics (add missing)
        DiagnosticError = { fg = colors.soft_red },
        DiagnosticWarn = { fg = colors.soft_red },
        DiagnosticHint = { fg = colors.light_brown },
        DiagnosticOk = { fg = colors.light_green },
        DiagnosticUnderlineError = { undercurl = true, sp = colors.soft_red },
        DiagnosticUnderlineWarn = { undercurl = true, sp = colors.soft_red },
        DiagnosticUnderlineInfo = { undercurl = true, sp = colors.gold },
        DiagnosticUnderlineHint = { undercurl = true, sp = colors.light_brown },
        DiagnosticUnderlineOk = { undercurl = true, sp = colors.light_green },
        DiagnosticVirtualTextError = { fg = colors.soft_red },
        DiagnosticVirtualTextWarn = { fg = colors.soft_red },
        DiagnosticVirtualTextInfo = { fg = colors.gold },
        DiagnosticVirtualTextHint = { fg = colors.light_brown },
        DiagnosticVirtualTextOk = { fg = colors.light_green },
        DiagnosticSignError = { fg = colors.soft_red },
        DiagnosticSignWarn = { fg = colors.soft_red },
        DiagnosticSignInfo = { fg = colors.gold },
        DiagnosticSignHint = { fg = colors.light_brown },
        DiagnosticSignOk = { fg = colors.light_green },

        -- LSP hover and floating windows
        LspInfoBorder = { fg = colors.tan, bg = colors.background },
        LspSignatureActiveParameter = { bg = colors.light_blue, bold = true },
        LspCodeLens = { fg = colors.tan },
        LspCodeLensSign = { fg = colors.tan },
        LspCodeLensSeparator = { fg = colors.tan },

        -- LSP references
        LspReferenceText = { bg = colors.light_blue },
        LspReferenceRead = { bg = colors.light_blue },
        LspReferenceWrite = { bg = colors.light_blue },

        -- LSP inlay hints
        LspInlayHint = { fg = colors.tan, italic = true },

        -- LSP semantic tokens
        ["@lsp.type.class"] = { fg = colors.strong_yellow },
        ["@lsp.type.comment"] = { fg = colors.tan },
        ["@lsp.type.decorator"] = { fg = colors.light_orange },
        ["@lsp.type.enum"] = { fg = colors.strong_yellow },
        ["@lsp.type.enumMember"] = { fg = colors.soft_pink },
        ["@lsp.type.event"] = { fg = colors.light_orange },
        ["@lsp.type.function"] = { fg = colors.strong_yellow },
        ["@lsp.type.interface"] = { fg = colors.strong_yellow },
        ["@lsp.type.keyword"] = { fg = colors.light_orange },
        ["@lsp.type.macro"] = { fg = colors.light_orange },
        ["@lsp.type.method"] = { fg = colors.strong_yellow },
        ["@lsp.type.modifier"] = { fg = colors.light_orange },
        ["@lsp.type.namespace"] = { fg = colors.white },
        ["@lsp.type.number"] = { fg = colors.light_green },
        ["@lsp.type.operator"] = { fg = colors.light_orange },
        ["@lsp.type.parameter"] = { fg = colors.orange },
        ["@lsp.type.property"] = { fg = colors.orange },
        ["@lsp.type.regexp"] = { fg = colors.orange2 },
        ["@lsp.type.string"] = { fg = colors.orange2 },
        ["@lsp.type.struct"] = { fg = colors.strong_yellow },
        ["@lsp.type.structMember"] = { fg = colors.orange },
        ["@lsp.type.typeParameter"] = { fg = colors.strong_yellow },
        ["@lsp.type.type"] = { fg = colors.strong_yellow },
        ["@lsp.type.variable"] = { fg = colors.white },
    }

    for group, opts in pairs(highlights) do
        vim.api.nvim_set_hl(0, group, opts)
    end
end

return M
